#!/bin/bash
set -o errexit
set -o xtrace

PROJECT='main'
BUILD_DIR='./build'
BIBER_ARGS=(--output-directory "$BUILD_DIR")
LATEX_ARGS=(-output-directory="$BUILD_DIR" -interaction=errorstopmode)

mkdir -p build
latex "${LATEX_ARGS[@]}" "$PROJECT"
biber "${BIBER_ARGS[@]}" "$PROJECT"
latex "${LATEX_ARGS[@]}" "$PROJECT"
pdflatex "${LATEX_ARGS[@]}" "$PROJECT"

